# Generated by Django 3.0.4 on 2020-03-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200330_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='icon',
            new_name='image',
        ),
    ]
