# Generated by Django 3.0.4 on 2020-03-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200330_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='image',
            new_name='icon',
        ),
    ]
