# Generated by Django 3.0.4 on 2020-03-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_saleorrent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleOrRent',
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('True', 'Satılık'), ('False', 'Kiralık')], max_length=10),
        ),
    ]
