# Generated by Django 3.0.4 on 2020-05-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_auto_20200515_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='location',
        ),
        migrations.AddField(
            model_name='house',
            name='area',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='bathroom',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='bedroom',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='city',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='house',
            name='country',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='house',
            name='district',
            field=models.CharField(default='-', max_length=70),
        ),
        migrations.AddField(
            model_name='house',
            name='garage',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='locationDetail',
            field=models.CharField(default='-', max_length=150),
        ),
    ]
