# Generated by Django 3.0.4 on 2020-05-14 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0013_house_userowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='houseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('1+0 Studio', '1+0 Studio'), ('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1', '4+1'), ('5+1', '5  +1')], max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10),
        ),
        migrations.AddField(
            model_name='house',
            name='houseType',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='house.houseType'),
        ),
    ]
