# Generated by Django 3.0.4 on 2020-05-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0014_auto_20200515_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housetype',
            name='status',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=25),
        ),
    ]
