# Generated by Django 3.0.4 on 2020-05-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0016_auto_20200515_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='buildTime',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
