# Generated by Django 3.0.4 on 2020-05-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0019_auto_20200515_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
