# Generated by Django 3.0.4 on 2020-05-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0020_auto_20200515_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.CharField(choices=[('Adana', 'Adana'), ('Adıyaman', 'Adıyaman'), ('Afyonkarahisar', 'Afyonkarahisar'), ('Ağrı', 'Ağrı '), ('Amasya', 'Amasya '), ('Ankara', 'Ankara '), ('Antaly', 'Antalya '), ('Artvin', 'Artvin '), ('Aydın ', 'Aydın '), ('Balıkesir', 'Balıkesir'), ('Bilecik ', 'Bilecik '), ('Bingöl ', 'Bingöl '), ('Bitlis ', 'Bitlis '), ('Bolu ', 'Bolu '), ('Burdur', 'Burdur '), ('Bursa ', 'Bursa '), ('Çanakkale', 'Çanakkale'), ('Çankırı ', 'Çankırı '), ('Çorum ', 'Çorum '), ('Denizli ', 'Denizli '), ('Diyarbakır', 'Diyarbakır '), ('Edirne ', 'Edirne '), ('Elazığ ', 'Elazığ '), ('Erzincan ', 'Erzincan '), ('Erzurum ', 'Erzurum '), ('Eskişehir', 'Eskişehir '), ('Gaziantep', 'Gaziantep '), ('Giresun ', 'Giresun '), ('Gümüşhane', 'Gümüşhane '), ('Hakkâri ', 'Hakkâri '), ('Hatay  ', 'Hatay '), ('Isparta ', 'Isparta '), ('Mersin ', 'Mersin '), ('Istanbul', 'İstanbul '), ('İzmir', 'İzmir '), ('Tekirdağ', 'Tekirdağ'), ('Tokat', 'Tokat '), ('Trabzon', 'Trabzon '), ('Tunceli', 'Tunceli '), ('Şanlıurfa', 'Şanlıurfa '), ('Uşak', 'Uşak '), ('Van', 'Van '), ('Yozgat', 'Yozgat'), ('Zonguldak', 'Zonguldak'), ('Aksaray', 'Aksaray '), ('Bayburt', 'Bayburt '), ('Karaman', 'Karaman '), ('Kırıkkale', 'Kırıkkale '), ('Batman', 'Batman '), ('Şırnak', 'Şırnak '), ('Bartın', 'Bartın '), ('Ardahan', 'Ardahan '), ('Iğdır', 'Iğdır '), ('Yalova', 'Yalova '), ('Karabük', 'Karabük '), ('Kilis', 'Kilis '), ('Osmaniye', 'Osmaniye'), ('Düzce', 'Düzce ')], max_length=50),
        ),
    ]
