# Generated by Django 3.0.4 on 2020-05-25 00:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0026_auto_20200525_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
