# Generated by Django 3.0.4 on 2020-05-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0027_house_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='KrediUygun',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], default='Hayır', max_length=10),
        ),
        migrations.AddField(
            model_name='house',
            name='cephe',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='house',
            name='esyaDurum',
            field=models.CharField(choices=[('Esyali', 'Esyali'), ('Esyasiz', 'Esyasiz')], default='Esyasiz', max_length=10),
        ),
        migrations.AddField(
            model_name='house',
            name='isinmatip',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='house',
            name='kat',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='house',
            name='katsayisi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='house',
            name='kullanimDurumu',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='house',
            name='takas',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='house',
            name='tapuDurumu',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='house',
            name='yapiTipi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
