# Generated by Django 3.0.4 on 2020-05-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0028_auto_20200525_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='cephe',
            field=models.CharField(choices=[('Güney', 'Güney'), ('Kuzey', 'Kuzey')], default='Güney', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='takas',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], default='Hayir', max_length=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='tapuDurumu',
            field=models.CharField(choices=[('Kat mülkiyetli tapu', 'Kat mülkiyetli tapu'), ('Kat irtifaklı tapu', 'Kat irtifaklı tapu'), ('Hisseli tapu', 'Hisseli tapu')], default='Kat irtifaklı tapu', max_length=30),
        ),
        migrations.AlterField(
            model_name='house',
            name='yapiTipi',
            field=models.CharField(choices=[('Kerpiç Bina', 'Kerpiç Bina'), ('Ahşap Bina', 'Ahşap Bina'), ('Yarı Kagir Bina', 'Yarı Kagir Bina'), ('Kagir Bina', 'Kagir Bina'), ('Betonarme Bina', 'Betonarme Bina'), ('Çelik  Bina', 'Çelik  Bina')], default='Betonarme Bina', max_length=25),
        ),
    ]
