# Generated by Django 3.0.4 on 2020-05-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0029_auto_20200525_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='aidat',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='kullanimDurumu',
            field=models.CharField(choices=[('Bos', 'Bos'), ('Dolu', 'Dolu')], default='bos', max_length=10),
        ),
    ]
