# Generated by Django 3.0.4 on 2020-05-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0030_auto_20200525_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='kimden',
            field=models.CharField(choices=[('Sahibinden', 'Sahibinden'), ('Emlak', 'Emlak')], default='Sahibinden', max_length=20),
        ),
    ]
