# Generated by Django 3.0.4 on 2020-05-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0031_house_kimden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='kat',
            field=models.IntegerField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='house',
            name='katsayisi',
            field=models.IntegerField(blank=True, max_length=255),
        ),
    ]
