# Generated by Django 3.0.4 on 2020-05-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0034_auto_20200525_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='katsayisi',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
